site_name: Test docs
site_description: 'A docs test'
site_author: 'iRobot'
site_url: https://alsora.github.io/test-docs

repo_name: 'alsora/test-docs'
repo_url: 'https://github.com/alsora/test-docs'

docs_dir: docs/

theme:
  name: 'material'

extra_css:
  - stylesheets/irobot-palette.css

nav:
    - Home: index.md
    - Getting Started:
      - Test: getting-started/test.md
      - Other test: getting-started/test2.md
