site_name: Test docs
site_description: 'A docs test'
site_author: 'iRobot'


docs_dir: docs/

theme:
  name: 'material'

extra_css:
  - stylesheets/irobot-palette.css

nav:
    - Home: index.md
    - Getting Started:
      - Test: getting-started/test.md
      - Other test: getting-started/test2.md
